version: '2'
services:
  mongodb:
    image: mongo
    volumes:
      - "./.data/db:/data/db"
  bot:
    build: .
    links:
      - mongodb
    env_file: tokens.env
    command: puma -b tcp://0.0.0.0:80 -e production src/server.ru
    ports:
      - "8801:80"